apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZmN3blBYMjRhZUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1ESXhNVEkzTURoYUZ3MHpOREV4TURBeE1UTXlNRGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURGQUtEUklYOU9FWU9wc1pCb3RLRE5lZ0xXTllCSE1TdWk3d2ZtN3hSZkJwUW9NdkRRYVA4VDJYS0cKcGZXRXBlaXZhM1JxL0NtRGFiVVhiQVlDTGJxdkJmSzhJUlZsQXFocC9mTFVDY0RGS3JSVDNJODBHZjVIK2hzOQpDN0tCL3NuU0YzVWxWZE12M3J5R0pxdUovMWRUTHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://dry-run-k8s-cluster.local:6443
  name: dry-run-cluster
contexts:
- context:
    cluster: dry-run-cluster
    user: dry-run-user
  name: dry-run-context
current-context: dry-run-context
kind: Config
preferences: {}
users:
- name: dry-run-user
  user:
    token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltTm1aa2xZTkZscGFYTndjMUZ6WlVKU1FtUklNVkp6YW5OVGRsOW5jbVZxVEhsSVgwdEdXRXRDYVdNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dGFtNWlZbllpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJakF4TWpNME5UWTNPQzA1TUdGaU1ERXlaRFF5T0RJeFlXSmpOV0UwT1RGbE1qUXdPRFEwTmpZaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZaR1ZtWVhWc2REcGtaV1poZFd4MEluMC5qV25RSnhFblpOYkc5d2tHWVVndGFfUWJXMmhaMkJXYzZYMWNBRGhFYnlzCg==